
imagesHost: ""
image: openpolicyagent/opa
imageTag: 0.24.0-envoy-1
imagePullPolicy: IfNotPresent

ingress:
  # namespace of the ingress containers
  # this will likely be different than the OPA namespace
  namespace: istio-system
  labelSelector:
    istio: ingressgateway

opa:
  replicas: 3
  port: 9191
  containerPort: 9191
  loglevel: info
  query: data.istio.authz.allow # this should never really change
  tls:
    enabled: false # TODO once we have cert manager
    secret: ""
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 25%
    type: RollingUpdate
  resources:
    requests:
      memory: "128Mi"
      cpu: "250m"
    limits:
      memory: "2Gi"
      cpu: "2"
  # Timeout defaults to 200ms if not specified. Setting it to 10s, an
  # arbitrary long timeout, provides sufficient overhead to resolve
  # CASMPET-1804/2570 "deadline exceeded" gRPC errors for the ext_authz filter.
  # A newer version of OPA might fix this with better performance.
  timeout: 10s


# To overide the default policy in files/policy.rego follow the example below
# NOTE: If the policy changes or is overriden, you MUST do a rolling restart of the
# OPA pods to pick them up until we stop mounting as a configmap.

# policy: |
#   # Istio Ingress Gateway OPA Policy
#   package istio.authz

#   default allow = true

# Run each opa pod on a separate worker when possible
affinity:
  podAntiAffinity:
     preferredDuringSchedulingIgnoredDuringExecution:
     - weight: 1
       podAffinityTerm:
         labelSelector:
           matchExpressions:
           - key: app.kubernetes.io/name
             operator: In
             values:
             - cray-opa
         topologyKey: kubernetes.io/hostname

jwtValidation:
  keycloak:
    jwksUri: "https://istio-ingressgateway.istio-system.svc.cluster.local/keycloak/realms/shasta/protocol/openid-connect/certs"
    issuers:
      # These are expected to be overriden via values.yaml customization.
      # XXX `shasta` is work-around until the CLI can support a separate
      # XXX URL for auth.
      shasta: "https://shasta.local/keycloak/realms/shasta"
      keycloak: "https://auth.local/keycloak/realms/shasta"
      # The following are deprecated and will be removed in the future
      gw_http: "http://api-gw-service-nmn.local/keycloak/realms/shasta"
      gw_https: "https://api-gw-service-nmn.local/keycloak/realms/shasta"
      internal_http: "http://keycloak:8080/keycloak/realms/shasta"
      mgmt_http: "http://mgmt-plane-cmn.local/keycloak/realms/shasta"
      mgmt_https: "https://mgmt-plane-cmn.local/keycloak/realms/shasta"
  spire:
    jwksUri: "https://istio-ingressgateway.istio-system.svc.cluster.local/spire-jwks-vshastaio/keys"
    issuers:
      vshasta.io: "http://spire.local/shasta/vshastaio"
