apiVersion: kuttl.dev/v1beta1
kind: TestSuite
commands:
- command: helm repo add cray-csm https://arti.dev.cray.com/artifactory/csm-helm-stable-local/
  ignoreFailure: true
- command: kubectl create ns ceph-rgw
- command: kubectl create ns cert-manager-init
- command: kubectl create ns istio-system
- command: kubectl create ns opa
- command: kubectl create ns services
- command: kubectl create ns sma
- command: kubectl create ns spire
- command: kubectl apply -f ./tests/kuttl/cray-configmap-ca-public-key.yaml
- command: helm install --wait -f ../../../cray-istio/kubernetes/cray-istio-operator/tests/kuttl/values.yaml --namespace istio-system cray-istio-operator ../../../cray-istio/kubernetes/cray-istio-operator
- command: helm install --wait -f ../../../cray-istio/kubernetes/cray-istio-deploy/tests/kuttl/values-disable-prometheus.yaml --namespace istio-system cray-istio-deploy ../../../cray-istio/kubernetes/cray-istio-deploy
- command: helm install --wait -f ../../../cray-istio/kubernetes/cray-istio/tests/kuttl/cray-certmanager-init.yaml --namespace cert-manager-init cray-certmanager-init cray-csm/cray-certmanager-init
- command: helm install --wait -f ../../../cray-istio/kubernetes/cray-istio/tests/kuttl/cray-certmanager.yaml --namespace cert-manager cray-certmanager cray-csm/cray-certmanager
- command: helm install --wait -f ../../../cray-istio/kubernetes/cray-istio/tests/kuttl/cray-certmanager-issuers.yaml --namespace cert-manager cray-certmanager-issuers cray-csm/cray-certmanager-issuers
- command: helm install -f ../../../cray-istio/kubernetes/cray-istio/tests/kuttl/values.yaml --namespace istio-system cray-istio ../../../cray-istio/kubernetes/cray-istio
- command: helm install -f ./tests/kuttl/values.yaml --namespace opa cray-opa .
testDirs:
- ./tests/kuttl
startKIND: true
kindNodeCache: true
