{{/*
MIT License

(C) Copyright 2021-2022 Hewlett Packard Enterprise Development LP

Permission is hereby granted, free of charge, to any person obtaining a
copy of this software and associated documentation files (the "Software"),
to deal in the Software without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense,
and/or sell copies of the Software, and to permit persons to whom the
Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included
in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
OTHER DEALINGS IN THE SOFTWARE.
*/}}
{{- range $name, $options:= .Values.ingresses }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cray-opa-{{ $name }}
  namespace: {{ $.Release.Namespace }}
spec:
  replicas: {{ $.Values.opa.replicas }}
  strategy:
    {{- $.Values.opa.strategy | toYaml | nindent 4}}
  selector:
    matchLabels:
      app.kubernetes.io/name: cray-opa-{{ $name }}
      app.kubernetes.io/instance: {{ $.Release.Name }}
      app.kubernetes.io/managed-by: {{ $.Release.Service }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cray-opa-{{ $name }}
        app.kubernetes.io/instance: {{ $.Release.Name }}
        app.kubernetes.io/managed-by: {{ $.Release.Service }}
    spec:
      containers:
      - image: {{ $.Values.image.repository }}:{{ $.Values.image.tag }}
        imagePullPolicy: {{ $.Values.image.pullPolicy }}
        name: opa-istio
        env:
          - name: POLICY_CONFIGMAP_VERSION
            # Change to force opa pods to restart and re-read ConfigMap.
            value: "7"
          {{- if $.Values.opa.httpTimeout }}
          - name: HTTP_SEND_TIMEOUT
            value: {{ $.Values.opa.httpTimeout | quote }}
          {{- end }}
        args:
          - run
          - --server
          {{- if $.Values.opa.tls.enabled }}
          - --tls-cert-file=/certs/tls.crt
          - --tls-private-key-file=/certs/tls.key
          {{- end }}
          - --log-level={{ $.Values.opa.loglevel }}
          - --config-file=/config/config.yaml
          - /policy/policy.rego
        volumeMounts:
          - mountPath: /config
            name: opa-istio-config
          - mountPath: /policy
            name: opa-policy
          {{- if $.Values.opa.tls.enabled }}
          - mountPath: /certs
            name: opa-certs
          {{- end }}
          - mountPath: /jwtValidationFetchTls
            name: fetch-jwt-certs-ca-vol
        resources:
          {{- $.Values.opa.resources | toYaml | nindent 10 }}
        ports:
        - name: http
          containerPort: {{ $.Values.opa.containerPort }}
        securityContext:
          runAsGroup: 65534
          runAsNonRoot: true
          runAsUser: 65534
      volumes:
      - configMap:
          name: istio-config-{{ $name }}
        name: opa-istio-config
      - configMap:
          name: opa-policy-{{ $name }}
        name: opa-policy
      {{- if $.Values.opa.tls.enabled }}
      - secret:
          secretName: {{ $.Values.opa.tls.secret }}
        name: opa-certs
      {{- end }}
      - configMap:
          name: cray-configmap-ca-public-key
        name: fetch-jwt-certs-ca-vol
      affinity:
      {{- if eq $.Values.affinity.default "preferred" }}
        podAntiAffinity:
           preferredDuringSchedulingIgnoredDuringExecution:
           - weight: 1
             podAffinityTerm:
               labelSelector:
                 matchExpressions:
                 - key: app.kubernetes.io/name
                   operator: In
                   values:
                   - cray-opa-{{ $name }}
               topologyKey: kubernetes.io/hostname
      {{- end }}
      {{- if eq $.Values.affinity.default "required" }}
        podAntiAffinity:
           requiredDuringSchedulingIgnoredDuringExecution:
             - labelSelector:
                 matchExpressions:
                 - key: app.kubernetes.io/name
                   operator: In
                   values:
                   - cray-opa-{{ $name }}
               topologyKey: kubernetes.io/hostname
      {{- end }}
      {{ if $options.affinity }}
{{ toYaml $options.affinity | indent 8 }}
      {{- end }}
      nodeSelector:
{{ toYaml $.Values.nodeSelector | indent 8 }}
      tolerations:
{{ toYaml $.Values.tolerations | indent 8 }}
{{- if $.Values.priorityClassName }}
      priorityClassName: {{ $.Values.priorityClassName }}
{{- end }}
{{- end }}
