apiVersion: v1
kind: Service
metadata:
  name: {{ include "cray-opa.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "cray-opa.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ports:
  - name: http
    port: {{ .Values.opa.port }}
    targetPort: http
  selector:
    app.kubernetes.io/name: {{ include "cray-opa.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}