{{- /*
Copyright 2022 Hewlett Packard Enterprise Development LP
*/ -}}
{{- range $name, $options := .Values.ingresses }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: opa-policy-{{ $name }}-base
  namespace: {{ $.Release.Namespace }}
data:
  policy.rego: |-
    # Base OPA Policy
    package istio.authz
    import input.attributes.request.http as http_request

    # Default return a 403 unless any of the allows are true
    default allow = {
      "allowed": false,
      "headers": {"x-ext-auth-allow": "no"},
      "body": "Unauthorized Request",
      "http_status": 403
    }
{{- end }}
